name: eduhash server CI/CD


on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  S3_BUCKET_NAME: eduhash-deploy

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./BackFinalPriject

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # application.properties 파일 생성    
    - name: Make application.properties      
      run: |        
        cd ./src/main/resources        
        touch ./application.properties                  
        echo "${{ secrets.APPLICATION_PROPERTIES }}" >> ./application.properties      
      shell: bash
      working-directory: ${{env.working-directory}}
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{env.working-directory}}

    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: ${{env.working-directory}}

#디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
      working-directory: ${{env.working-directory}}

    - name: Copy appspec.yml to deploy
      run: cp appspec.yml ./deploy
      working-directory: ${{env.working-directory}}

    - name: Copy deploy.sh to deploy
      run: cp deploy.sh ./deploy
      working-directory: ${{env.working-directory}}

# Jar파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy
      working-directory: ${{env.working-directory}}

    - name: Make zip file
      run: zip -r ./eduhash.zip ./deploy
      shell: bash
      working-directory: ${{env.working-directory}}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./eduhash.zip s3://$S3_BUCKET_NAME/

# Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-northeast-2
      run:
        aws deploy create-deployment
        --application-name eduhash
        --deployment-group-name eduhash-group
        --file-exists-behavior OVERWRITE
        --s3-location bucket=eduhash-deploy,bundleType=zip,key=eduhash.zip
        --region ap-northeast-2
